### PR TITLE
Security and functionality improvements

### PR DESCRIPTION
**Pull request by bbilyeu**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Yes, there are a few breaking changes.

1. `logconnect` has been changed to `dontLogTCPWrappersConnects` which identically matches the snmpd.conf option (instead of forcing a formula specific value).
2. `syscontact` changed to `sysContact` to also match the snmpd.conf option.
3. `location` changed to `sysLocation` to also match the snmpd.conf option.
4. The kitchen workflow now prefers docker over vagrant for performance and simplicity, as it matches the behavior in other saltstack formula repositories.

### Describe the changes you're proposing

- First and foremost, this addresses the SNMP user/pass being dumped into snmpd.conf in plaintext. 
  - The specific workflow for Deb/RHEL systems is test SNMP access with credentials -> (on fail) stop snmpd -> add createUser string to the correct config file (/var/lib/____/snmpd.conf) -> start snmpd back up. Doing so will cause the credentials to be "consumed", converted into something no longer human readable. 
- Second, it standardizes a lot of the options and moves closer to the saltstack formula recommendation of "sane default values".

### Pillar / config required to test the proposed changes

Can be tested via updated kitchen.

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [x] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [x] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@bbilyeu Thanks for this PR.  Since this is bringing in standardisation based on other formula repos, I'll be able to review parts of this using the `ssf-formula` (which is used for standardisation across ~100 repos in the org).  However, we may need to break this up in blocks to make it easier to review.  Separating the refactoring and CI updates from the new features and breaking changes.

@alxwr Could you help us to figure things out better here?  How would you prefer to review all of this?

**Comment by bbilyeu** [comment]
@myii Fair enough! Since a lot of this is interconnected, I can resubmit it next week in a more "compartmentalized" fashion, but it will still need to more or less together. For what it's worth: the single kitchen test was updated to allow for relatively low effort validation. 

Just let me know what I can do to make this easier on you and alxwr :)

**Comment by bbilyeu** [comment]
@myii I'm going to close this and resubmit an organized, concise version. Apologies for the extra noise :)

**Comment by myii** [comment]
@bbilyeu Let me help make things a bit smoother.  I'll push through the standardisation changes first, so that you can base your changes on top of that.  I think that will make things easier all round.  I'll let you know when it's ready; should be able to provide that within the next day.

**Comment by myii** [comment]
> ... I'll push through the standardisation changes first, so that you can base your changes on top of that.

@bbilyeu I've implemented `semantic-release` for this formula in #44.  You should find it a lot simpler to add your new feature now.  Tests are also running across all Linux platforms and FreeBSD.

**Pull request closed without merging**
